### PR TITLE
Added the ability to add recurring exceptions

### PR DESCRIPTION
**Pull request by joshuadegier**
This was requested in https://github.com/spatie/opening-hours/issues/39, this PR adds the ability to add `recurring_exceptions`, the array accepts a `m-d` format key and an array with values similar to a day or the exceptions.

```php
$openingHours = Spatie\OpeningHours\OpeningHours::create([
    'monday' => ['00:00-22:00'],
    'thursday' => ['01:00-18:00'],
    'exceptions' => [
        '2018-01-01' => ['00:00-19:00'],
    ],
    'recurring_exceptions' => [
        '01-01' => [],
        '12-25' => ['09:00-12:00'],
        '12-26' => [],
    ],
]);
```

So in the above example, when requesting the opening hours for 1st of january 2018, the code first checks if the full date (2018-01-01) is present, if so, these times are being returned. Otherwise it checks against d-m (01-01) in the recurring_exceptions key and if nothing is found, it returns the day.

The PR is backed up with a test that shows that it works and it doesn't break current functionality:

```php
    /** @test */
    public function it_can_determine_that_its_open_at_a_certain_date_and_time_on_an_recurring_exceptional_day()
    {
        $openingHours = OpeningHours::create([
            'monday' => ['09:00-18:00'],
            'recurring_exceptions' => [
                '01-21' => [],
                '12-25' => ['09:00-12:00'],
                '12-26' => [],
            ],
        ]);

        $closedOnNewYearDay = new DateTime('2017-01-01 11:00:00');
        $this->assertFalse($openingHours->isOpenAt($closedOnNewYearDay));
        $this->assertTrue($openingHours->isClosedAt($closedOnNewYearDay));

        $closedOnSecondChristmasDay = new DateTime('2025-12-16 12:00:00');
        $this->assertFalse($openingHours->isOpenAt($closedOnSecondChristmasDay));
        $this->assertTrue($openingHours->isClosedAt($closedOnSecondChristmasDay));

        $openOnChristmasMorning = new DateTime('2025-12-25 10:00:00');
        $this->assertTrue($openingHours->isOpenAt($openOnChristmasMorning));
        $this->assertFalse($openingHours->isClosedAt($openOnChristmasMorning));
    }
```

### CODE REVIEW

**Comment by joshuadegier** [comment]
Did a refactor to reduce the amount of code needed to get this working. The `recurring_exceptions` is unnecessary now, the code checks the date format against `Y-m-d` or `m-d` and adds the exceptions accordingly.

Code still checks for full dates first before looking for exceptions on a recurring date. All tests are refactored and no breaking changes.

**Comment by sebastiandedeyne** [comment]
Looks good at first sight! I'll give this a thorough review tomorrow :)

**Comment by sebastiandedeyne** [comment]
All good 👌 

Thanks!

**Comment by joshuadegier** [comment]
Great to hear. You're welcome!

**Pull request merged**
