### PR TITLE
adding nextClose and corresponding tests

### PR DESCRIPTION
**Pull request by jerome2710**
Created pull request for issue #55.

### CODE REVIEW

**Comment by freekmurze** [comment]
Could you add a few examples of these new functions to the readme?

**Comment by jerome2710** [comment]
Been there, done that.

**Comment by miclf** [comment]
Seems to me the examples in the README have to be changed. So far, they’re [exact copies](https://github.com/spatie/opening-hours/commit/c18f306444841485d251230709c0c51e95c21d12#diff-04c6e90faac2675aa89e2176d2eec7d8) of the examples for `nextOpen()` and, as such, they do not reflect the new feature (because the datetimes are incorrect).

I suggest the following (please correct in case I’m wrong):
```
// 2016-12-24 12:00:00
$nextClose = $openingHours->nextClose(new DateTime('2016-12-24 10:00:00'));

// 2016-12-26 12:00:00
$nextClose = $openingHours->nextClose(new DateTime('2016-12-25 15:00:00'));
```

**Comment by freekmurze** [comment]
@miclf could you PR that?

**Comment by miclf** [comment]
@freekmurze Sure. See #69.

I also improved a few tiny other details along the way.

**Pull request merged**
