### PR TITLE
#88 Add the ability to overflow times into the next day

### PR DESCRIPTION
**Pull request by rlweb**
See #88 I've gone for the additional parameter set on construction. To note, I've left the overlapping function `mergeOverlappingRanges` as I feel it'll be beyond what the function should be doing to remove overlapping times across days.

I've also added structured data to the README.md

### CODE REVIEW

**Comment by kylekatarnls** [comment]
Hi,

Thanks, very good job. I also approve the timezone option you added.

Here is why I'm not a fan of boolean flags. https://phpmd.org/rules/cleancode.html

I used them before, and stumbled in many pitfalls:

- The PHPMD rule: keep a single role to each method (including the constructor).
- Next time you need an on/off option you add one more, then one day, your constructor looks like: `new MyClass("foo", true, false, false, true)` making you like writing binary stuff and never know what is each boolean. The same goes for the "holes" to fill with `null`.
- If someone extends the class and the constructor, when he will update, he will get an error: incompatible function definition.
- Someday you realize, there are other nice overflow modes to have, you will need to transform your boolean to an other type string/int, and have to keep the method prototype backward-compatible that make the code and function definition very unclear.

An other advantage if the overflow option is in the array definition, you can change it when you change opening hours using `fill` method.

Does the boolean flag feels really needed for some reason to you? Else would you agree to consider the `'allow_overflow' => true` option in the array definition?

**Comment by rlweb** [comment]
Hi @kylekatarnls , Thanks for the comment! Ah, yes I agree with the adding the booleans to the constructor can become messy rather quickly. I would favor having setters on the class such as `->enableOverflow()` which could be called after class construction. How would you feel about this?

**Comment by kylekatarnls** [comment]
It would be great but I don't see how you could do it without postponing `parseOpeningHoursAndExceptions` called in `fill` which throw the exception on failure. So it will not allow to do it using `create`, you will have to call `(new OpeningHours)->enableOverflow()->fill($hours)` to enable the option before filling hours. It's fine for me but it's a bit more tricky than the current `create` method.

**Comment by rlweb** [comment]
I've just had a quick test and it seems there's no exception throw for overfilling times! But good point I'll make it an array of options that can be passed in on the construction

**Comment by kylekatarnls** [comment]
What about having the options inside the array-definition `$data` (first parameter of `fill()` method? It could be the same way we already extract `$metaData`.

**Pull request merged**
